# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: cert-manager-cainjector-leaderelection
#   namespace: cert-manager
# rules:
# - apiGroups: ["coordination.k8s.io"]
#   resources: ["leases"]
#   verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: cert-manager-cainjector-leaderelection
#   namespace: cert-manager
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: cert-manager-cainjector-leaderelection
# subjects:
# - kind: ServiceAccount
#   name: cert-manager-cainjector
#   namespace: cert-manager


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-leaderelection
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-leaderelection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-leaderelection
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
