apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-repl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-repl
  template:
    metadata:
      labels:
        app: router-repl
    spec:
      containers:
        - name: router
          image: your-dockerhub-user/router-repl:latest
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: router-repl
spec:
  selector:
    app: router-repl
  ports:
    - port: 80
      targetPort: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: "*.codevo.dev"
      http:
        paths:
          - path: /(.*)   #matches literally every possible path a user might visit
            pathType: Prefix
            backend:
              service:
                name: router-repl
                port:
                  number: 80  # HTTP port exposed by router-repl service
